### ISSUE TITLE
image url customer company log incorrect (https)

### ISSUE THREAD

**Issue by rolero** [niteosoft/simplejobscript#3]
Uploaded a customer logo to sjs as a customer. 

https://www.88careers.com/job/fullstack-developer-at-blue-orange-shanghai/492

Image can not be found. 

When I inspect the img src:
`<a href="/jobs-at/blue-orange/572"><img itemprop="image" class="co-logo" src="http://s://www.88careers.com/uploads/companies/1561690347_ß¦¦+logoDz - kopie (Aangepast).jpg" alt="company logo"></a>`

It seems something goes wrong when using https.

**Comment by rolero** [comment]
Fixed it by update configs.envs.php:

before
`'protocol' => 'http://', // "http://" or "https://"
		'prefix' => 'https://www.88careers.com/', // main url of the app "domainname.com", without "http://" or "www"`

after

`
'protocol' => 'https://', // "http://" or "https://"
		'prefix' => 'www.88careers.com/', // main url of the app "domainname.com", without "http://" or "www"`

It seems that the installation procedure does not take care of this correctly.

**Comment by niteosoft** [comment]
Yes the https needs to be activated.
