### ISSUE TITLE
Incorrect html: html elements with the same id on job page

### ISSUE THREAD

**Issue by rolero** [niteosoft/simplejobscript#4]
![image](https://user-images.githubusercontent.com/2805313/60314933-18669c00-9997-11e9-9107-8f0a7b6a11bb.png)

**Comment by niteosoft** [comment]
This is because of 2 types of forms are being used. One for job seekers that are logged in - applying with an existing profile and the other form is for job seekers without a profile. We consider this warning not an error or bug hence probably for the time being it will not be changed.
