### ISSUE TITLE
Feature request: wysiwyg editor: add html view

### ISSUE THREAD

**Issue by rolero** [niteosoft/simplejobscript#5]
Feature request: 

Would in be possible to add "html view/edit" to the tinyMCE editor in the backend? Some time ago I copied some text from a website. Afterwards noticed there where some html element in the text that I wanted to remove. I was not able due to the fact i could not see them in the tinyMCE editor. Had to remove them by editing the record using SQL.

**Comment by niteosoft** [comment]
Wysiwyg editor used in SJS is a third party tool which we integrated but have no power over. Any new functionality needed in tinyMCE depends solely on authors of this software. 

Take a look at:
https://www.tiny.cloud/docs/plugins/code/

I see there is some plugin which allows users to edit HTML code.
You can download and include it into your project.
TinyMCE initialization takes place in:
js/functions.js file - InitEditor() function.

Thank you for suggestion.
